---
- name: Add Jenkins helm repo
  become_user: vagrant
  command: helm repo add jenkins https://charts.jenkins.io

- name: Update helm repo
  become_user: vagrant
  command: helm repo update

- name: Install Jenkins
  become_user: vagrant
  command: |
    helm install jenkins jenkins/jenkins \
      --namespace jenkins --create-namespace \
      --set controller.serviceType=NodePort
