apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devhub-ingress-dev
  namespace: devhub-frontend-dev
spec:
  rules:
    - host: devhub.local
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: devhub-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devhub-frontend
                port:
                  number: 80