apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devhub-ingress
  namespace: devhub-frontend
spec:
  rules:
    - host: devhub.local
      http:
        paths:
          # 백엔드 API
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: devhub-backend
                port:
                  number: 8080
          # 프론트 SPA
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devhub-frontend
                port:
                  number: 80
