apiVersion: v1
kind: Service
metadata:
  name: devhub-frontend
  namespace: devhub-frontend
spec:
  type: ClusterIP
  selector:
    app: devhub-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devhub-backend
  namespace: devhub-frontend
spec:
  type: ExternalName
  externalName: devhub-backend.devhub-backend.svc.cluster.local