---
- name: Install ArgoCD
  become_user: vagrant
  command: kubectl apply -n kube-system -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Patch ArgoCD server to NodePort
  become_user: vagrant
  shell: |
    kubectl -n kube-system patch svc argocd-server \
      -p '{"spec": {"type": "NodePort"}}'
