- name: Test Ansible Connection
  hosts: devhub
  tasks:
    - name: Ping test
      ping:

    - name: Display current user
      command: whoami
      register: result

    - debug:
        msg: "Connected as user {{ result.stdout }}"