apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhub-frontend
  namespace: devhub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devhub-frontend
  template:
    metadata:
      labels:
        app: devhub-frontend
    spec:
      containers:
        - name: frontend
          image: goonerd/devhub-frontend-dev:devhub-frontend-20251115-58
          ports:
            - containerPort: 80
          env:
            - name: API_BASE
              value: http://devhub-backend.devhub-backend.svc.cluster.local:8080/v1
