apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhub-frontend
  namespace: devhub-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devhub-frontend
  template:
    metadata:
      labels:
        app: devhub-frontend
    spec:
      containers:
        - name: frontend
          image: goonerd/devhub-frontend-dev:devhub-frontend-20251120-83
          ports:
            - containerPort: 80
          env:
            - name: API_BASE
              value: http://devhub-backend.devhub-backend-dev.svc.cluster.local:8080/v1
