apiVersion: apps/v1
kind: Deployment
metadata:
  name: devhub-frontend
  namespace: devhub-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devhub-frontend
  template:
    metadata:
      labels:
        app: devhub-frontend
    spec:
      containers:
        - name: frontend
          image: goonerd/devhub-frontend-dev:devhub-frontend-20251126-97
          ports:
            - containerPort: 80
          env:
            - name: API_BASE
              value: http://devhub-backend.devhub-backend-dev.svc.cluster.local:8080/v1
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: devhub-frontend-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devhub-frontend-nginx
  namespace: devhub-frontend-dev
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
---