---
- name: Minikube 설치 스크립트 다운로드
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: kubectl 설치
  get_url:
    url: https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
