---
- name: Jenkins 설치를 위한 Java 설치
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Jenkins GPG 키 추가
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Jenkins repo 추가
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Jenkins 설치
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Jenkins 서비스 시작 및 자동 실행 설정
  service:
    name: jenkins
    state: started
    enabled: yes
