---
- name: Initialize Kubernetes Master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/pki

- name: Setup kubeconfig for vagrant user
  become_user: vagrant
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown vagrant:vagrant $HOME/.kube/config

- name: Install Flannel CNI
  become_user: vagrant
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: Create join command script
  shell: kubeadm token create --print-join-command > /vagrant/join.sh
